#!/usr/bin/env sh

set -ue

SCRIPT_PATH=$(cd $(dirname $0) && pwd)
CMAKE_PATH=$SCRIPT_PATH/..
BUILD_PATH=$SCRIPT_PATH/../build/proj_xcode

MICROPHONE_DEMO=NONE

if [ $# -ne 0 ]; then
  MICROPHONE_DEMO="$1"
else
  PS3="Select the demo type number to use: "
  select var in 'SoundFile' 'Microphone'
  do
    case "$var" in
      'SoundFile' ) MICROPHONE_DEMO=OFF ;;
      'Microphone' ) MICROPHONE_DEMO=ON ;;
      * ) echo "Invalid option $REPLY." ;;
    esac
    break
  done
fi

if [ "$MICROPHONE_DEMO" = NONE ]; then
  exit -1
fi

# Run CMake.
cmake -S "$CMAKE_PATH" \
  -B "$BUILD_PATH" \
  -D CSM_MOTIONSYNC_MICROPHONE_DEMO="$MICROPHONE_DEMO" \
  -G Xcode
